### ISSUE TITLE
iam_role.json missing permission?

### ISSUE THREAD

**Issue by stephenmogg** [SUSE-Enceladus/suse-rancher-setup#114]
Running through an install, I think the installer needs:
"ec2:DescribeSecurityGroups",
as one of the permissions in the policy.  

This does not appear to be in the sample policy.
https://github.com/SUSE-Enceladus/suse-rancher-setup/blob/main/aws-iam/iam_role.json

Once added, the install progressed.

**Comment by bear454** [comment]
What region was this in?

**Comment by stephenmogg** [comment]
US EAST 1 Virginia?
Will try Ireland tomorrow.


From: James Mason ***@***.***>
Date: Wednesday, 21 September 2022 at 18:04
To: SUSE-Enceladus/suse-rancher-setup ***@***.***>
Cc: Stephen Mogg ***@***.***>, Author ***@***.***>
Subject: Re: [SUSE-Enceladus/suse-rancher-setup] iam_role.json missing permission? (Issue #114)

What region was this in?

**Comment by stephenmogg** [comment]
BTW – just tried again today in EU-West-1 and it works fine.

(I’ll try us-east-1 again tomorrow)

Stephen

From: James Mason ***@***.***>
Date: Wednesday, 21 September 2022 at 18:04
To: SUSE-Enceladus/suse-rancher-setup ***@***.***>
Cc: Stephen Mogg ***@***.***>, Author ***@***.***>
Subject: Re: [SUSE-Enceladus/suse-rancher-setup] iam_role.json missing permission? (Issue #114)

What region was this in?

**Comment by bear454** [comment]
We have observed that it is possible that both administrative-level configuration of accounts, and prior operations in an account,  can affect the required permissions. It's entirely possible you may discover a permission required only in certain regions, or only one-time in a new account (see #107 for example).

**Comment by bear454** [comment]
For reference, this would be called by https://github.com/SUSE-Enceladus/suse-rancher-setup/blob/main/engines/aws/app/models/aws/security_group.rb#L18
