### ISSUE TITLE
Cleanup issues are not handled properly

### ISSUE THREAD

**Issue by bear454** [SUSE-Enceladus/suse-rancher-setup#121]
In the event that a cleanup step has an error, execution stops, but the UI continues to act as if cleanup is in progress.

Here's a snippet from `cli.log`:
```
 I, [2022-09-28T23:01:18.610900 #552]  INFO -- : Executing "aws ec2 delete-subnet --subnet-id subnet-089ea7f29dbb1c171".
E, [2022-09-28T23:01:19.512709 #552] ERROR -- : Error output: 
E, [2022-09-28T23:01:19.512814 #552] ERROR -- : Error output: An error occurred (DependencyViolation) when calling the DeleteSubnet operation: The subnet 'subnet-089ea7f29dbb1c171' has dependencies and cannot be deleted.
E, [2022-09-28T23:01:19.578970 #552] ERROR -- : Status: 255
```

... that's the end of the log, but 15 minutes later, the 'cleaning resources' icon is still spinning.

We need to detect when an error occurs during cleanup. Ideally, we would retry over a timed backoff period, but at some point we need to notify the user that the remaining resources will need to be cleaned up manually.

**Comment by jesusbv** [comment]
I don't know what error produced that behaviour but, a standard error during cleaning up makes the progress stop

If it did not, it is possible the error is not being captured/handled properly

**Comment by bear454** [comment]
Well, the background process stopped when the error occurred (retcode 255), but the UI continued to refresh - giving the perception that the process is ongoing (when it is not).

**Comment by bear454** [comment]
Here's a possible solution for implementing retries: https://github.com/kamui/retriable
