### ISSUE TITLE
Improve usability of "Clean resources commands"

### ISSUE THREAD

**Issue by asmorodskyi** [SUSE-Enceladus/suse-rancher-setup#123]
Some ideas how to make this feature more handy : 
1. "Download cleanup as file" sounds like more appropriate text on button
2. Don't see good reason to pack single file which weights 4 KB into zip archive . It is one extra step when you want to execute it 
3. Whole design of "Next steps" looks a bit messy ( e.g. two sets of same buttons , two pieces of "wall of text" ) I would simplify it : 
               -  No need for "Generate clean up commands" button it is overkill , this process should just happen in background
               -  We can replace list of created resources by button which allows to download them as another file 
      So we will have text till  `When you are ready to upgrade your Rancher instance, please see the Rancher documentation for details`  and than just 3 buttons "Cleanup resources" , "Download cleanup as file" , "Download created resources"

**Comment by bear454** [comment]
I agree we need to do some re-design on the "Next Steps" page (and probably break out the cleanup into a separate step).

**Comment by bear454** [comment]
Related: #125
