### ISSUE TITLE
"helm uninstall " commands from cleanup commands contains non-existing flags

### ISSUE THREAD

**Issue by asmorodskyi** [SUSE-Enceladus/suse-rancher-setup#124]
`KUBECONFIG=/tmp/kubeconfig helm uninstall rancher-stable --namespace cattle-system --output json` - will produce error because helm command does not have "--region" and "--output" flags

**Comment by bear454** [comment]
:thinking: The `helm` deploys don't really need to be rolled back at all - they're inherently destroyed when the nodegroup is destroyed.
